### ISSUE TITLE
Rewrite Source Code into Typescript

### ISSUE THREAD

**Issue by jvanderen1** [solidjs/solid-styled-components#29]
Hello 👋🏻 

I was wondering if the author would be open to having the source code rewritten in Typescript? Having first-class Typescript support would ensure that the code stays type conformant and allows types to built at compile time.

I would love to give this a shot during my spare time, but only if the author would be open to it.

Thanks,
Josh

**Comment by ryansolid** [comment]
It was TS but I changed it because the types weren't compatible with upstream library goober that made a bunch of assumptions based on React/Preact. I basically realized I'd need to hand write the types myself and just gave up. If some TS wizard can make things work I'm all for it, but this was an example where agnostic JSX as an assumption is a bit of a myth.

**Comment by jvanderen1** [comment]
I am working on a prototype now just to see what it would be like! I have the functions separated out into Typescript files. A few things left:
- Get correct typings across project
- Ensure Typescript can build properly. I chose to use [Parcel](https://parceljs.org/) as a zero-config bundler to generate *.cjs, *.mjs, and types.d.ts files for us.

https://github.com/jvanderen1/solid-styled-components/tree/jvanderen1-29

**Comment by ryansolid** [comment]
Hmm.. nothing against Parcel but we do generally use Rollup around here. Mind you this project doesn't use JSX, at least currently so the template we often use doesn't make sense: https://github.com/amoutonbrady/rollup-preset-solid

Mind I'm not too worried about that. If we ever changed to use JSX or the `<Dynamic>` component swapping around is easy as long as the TS works. Mostly just a control thing, since with JSX projects we ship the JSX source and ESM only instead of CJS because server side libraries need to compile within their own projects. (Compilation in Node modules with Babel doesn't go well in Parcel which is part of the reason you don't see it used with Solid as often for libraries). Also rollup tends to produce the smallest bundles but I don't know if that will come to play here, but I'd definitely be interested in the output.

**Comment by jvanderen1** [comment]
That's definitely good insight! I didn't actually take the time to see what bundlers were used outside of this project. I mainly chose it for the purpose of quickly compiling this into multiple formats.

However, if Rollup is the official bundler of choice, I can look into integrating it instead 👍🏻.

**Comment by jvanderen1** [comment]
Unfortunately, I am going to stop pursuing this.

After configuring a few things around, I find that the types provided by Goober do not match the API's. For example, in Goober's `css` function, `props` values here can also be functions: https://github.com/solidjs/solid-styled-components/blob/46397b2b1997d8d05ed1a397180509f3273570a8/src/index.d.ts#L18

I did notice some small nit's in our codebase though that I can make separate PR for though.

But re-writting the codebase into Typescript seems infeasible at the moment. If anyone is curious where I left off, here's my repo: https://github.com/jvanderen1/solid-styled-components/tree/jvanderen1-29/src

**Comment by ryansolid** [comment]
I understand but appreciate the effort.
